llm:
  type: openai
  endpoint: http://llm:8080/v1
  model_env: OAI_MODEL
asr:
  type: whisper
  endpoint: http://asr:9000
tts:
  type: piper
  endpoint: http://tts:9001
vision:
  type: rtsp
  endpoint: rtsp://vision:8554/unicast
periph:
  type: periph
  endpoint: http://periph:7000
